import type { Project } from './types';

// One record = one garage bay. status: 'in-progress' renders a closed shutter;
// flipping a bay open later is a one-field change.
export const projects: Project[] = [
  {
	slug: 'blackboard',
	title: 'blackboard.ai',
	shutterTitle: 'BlackBoard.ai',
	blurb: 'An IEP/504-compliant classroom platform — teachers upload lesson notes, a compliance agent checks them against each students accommodation profile and auto-generates personalized audit-ready lesson variants.',
	chips: ['Butterbase', 'EverMind OS', 'RAG'],
	itag: '▶ video demo',
	status: 'open',
	tile: 'text',
  },
  {
    slug: 'datascout',
    title: 'DataScout',
    shutterTitle: 'DataScout',
    blurb: 'Natural-language dataset discovery — Bedrock (Claude) intent extraction over an OpenSearch index, serverless on AWS.',
    chips: ['Claude API', 'Lambda', 'CDK'],
    itag: '▶ video demo + Devpost',
    status: 'open',
    tile: 'text',
  },
  {
    slug: 'emotion-gan',
    title: 'Emotion GAN',
    shutterTitle: 'Emotion GAN',
    blurb: 'DCGAN-generated synthetic samples for underrepresented emotion classes — and an honest read on where synthetic data falls short.',
    chips: ['PyTorch', 'DCGAN', 'CNNs'],
    itag: '⟳ rotating pipeline cards',
    status: 'open',
    tile: 'text',
    tileText: 'UCD',
  },
  {
    slug: 'aviran-lab',
    title: 'PaRPI / BRIDGE',
    shutterTitle: 'Aviran Lab',
    shutterBlurb: 'RNA–protein interaction models — opens when the work ships.',
    blurb: 'Multimodal feature integration (GraphConv, cross-attention) in a state-of-the-art RNA–protein interaction model.',
    chips: ['Research', 'Transformers'],
    itag: '◼ in progress',
    status: 'in-progress',
    tile: 'text',
    tileText: 'RNA',
  },
  {
    slug: 'karzand-lab',
    title: 'InfoBoost proxies',
    shutterTitle: 'Karzand Lab',
    shutterBlurb: 'Information-theoretic transfer learning — opens when the work ships.',
    blurb: 'Do heuristic proxies track true mutual information and KL divergence? Closed-form Gaussian experiments.',
    chips: ['Research', 'Info theory'],
    itag: '◼ in progress',
    status: 'in-progress',
    tile: 'text',
    tileText: 'I(X;Y)',
  },
  {
    slug: 'lane-segmentation',
    title: 'Monocular perception',
    shutterTitle: 'Lane Segmentation',
    shutterBlurb: 'EcoCAR senior design — monocular perception, opens when it ships.',
    blurb: 'Lane segmentation + vehicle tracking cutting autonomous sensory requirements 85%.',
    chips: ['Research', 'EcoCAR'],
    itag: '◼ in progress',
    status: 'in-progress',
    tile: 'text',
    tileText: 'CAV',
  },
];
